import utest.Assert;
import utest.Runner;
import utest.ui.Report;

import ufront.core.FuturoidTest;
import ufront.core.AcceptEitherTest;
import ufront.core.MultiValueMapTest;
import ufront.core.SyncTest;
import ufront.app.UfrontApplicationTest;
import ufront.app.HttpApplicationTest;
import ufront.handler.ErrorPageHandlerTest;
import ufront.handler.RemotingHandlerTest;
import ufront.handler.MVCHandlerTest;
import ufront.handler.DispatchHandlerTest;
import ufront.log.FileLoggerTest;
import ufront.log.MessageTest;
import ufront.log.RemotingLoggerTest;
import ufront.log.BrowserConsoleLoggerTest;
import ufront.web.HttpErrorTest;
import ufront.web.DispatchControllerTest;
import ufront.web.context.HttpResponseTest;
import ufront.web.context.ActionContextTest;
import ufront.web.context.HttpRequestTest;
import ufront.web.context.HttpContextTest;
import ufront.web.DefaultUfrontConfigurationTest;
import ufront.web.HttpCookieTest;
import ufront.web.ControllerMacrosTest;
import ufront.web.UserAgentTest;
import ufront.web.session.InlineSessionMiddlewareTest;
import ufront.web.session.VoidSessionTest;
import ufront.web.session.FileSessionTest;
import ufront.web.result.DetoxResultTest;
import ufront.web.result.ViewResultTest;
import ufront.web.result.ContentResultTest;
import ufront.web.result.RedirectResultTest;
import ufront.web.result.FileResultTest;
import ufront.web.result.JsonResultTest;
import ufront.web.result.BytesResultTest;
import ufront.web.result.EmptyResultTest;
import ufront.web.result.FilePathResultTest;
import ufront.web.result.ActionResultTest;
import ufront.web.url.PartialUrlTest;
import ufront.web.url.filter.DirectoryUrlFilterTest;
import ufront.web.url.filter.SegmentToParamUrlFilterTest;
import ufront.web.url.filter.QueryStringUrlFilterTest;
import ufront.web.url.filter.PathInfoUrlFilterTest;
import ufront.web.url.VirtualUrlTest;
import ufront.web.ControllerTest;
import ufront.web.upload.TmpFileUploadSyncTest;
import ufront.web.upload.TmpFileUploadMiddlewareTest;
import ufront.web.DispatchTest;
import ufront.web.DefaultControllerTest;
import ufront.web.UfrontConfigurationTest;
import ufront.view.UFViewEngineTest;
import ufront.view.FileViewEngineTest;
import ufront.view.TemplateDataTest;
import ufront.view.TemplatingEnginesTest;
import ufront.view.UFTemplateTest;
import ufront.api.ApiMacrosTest;
import ufront.api.UFApiTest;
import ufront.api.UFApiContextTest;
import ufront.cache.MemoryCacheTest;
import ufront.sys.SysUtilTest;
import ufront.test.TestUtilsTest;
import ufront.auth.YesBossAuthHandlerTest;
import haxe.remoting.RemotingUtilTest;
import haxe.remoting.HttpAsyncConnectionWithTracesTest;
import haxe.remoting.HttpConnectionWithTracesTest;

class TestMain
{
	static function main(){
		var runner = new Runner();
		addTests( runner );
		Report.create(runner);
		runner.run();
	}
	
	static function addTests( runner:Runner ) {
		runner.addCase( new ufront.core.FuturoidTest() );
		runner.addCase( new ufront.core.AcceptEitherTest() );
		runner.addCase( new ufront.core.MultiValueMapTest() );
		runner.addCase( new ufront.core.SyncTest() );
		runner.addCase( new ufront.app.UfrontApplicationTest() );
		runner.addCase( new ufront.app.HttpApplicationTest() );
		runner.addCase( new ufront.handler.ErrorPageHandlerTest() );
		runner.addCase( new ufront.handler.RemotingHandlerTest() );
		runner.addCase( new ufront.handler.MVCHandlerTest() );
		runner.addCase( new ufront.handler.DispatchHandlerTest() );
		runner.addCase( new ufront.log.FileLoggerTest() );
		runner.addCase( new ufront.log.MessageTest() );
		runner.addCase( new ufront.log.RemotingLoggerTest() );
		runner.addCase( new ufront.log.BrowserConsoleLoggerTest() );
		runner.addCase( new ufront.web.HttpErrorTest() );
		runner.addCase( new ufront.web.DispatchControllerTest() );
		runner.addCase( new ufront.web.context.HttpResponseTest() );
		runner.addCase( new ufront.web.context.ActionContextTest() );
		runner.addCase( new ufront.web.context.HttpRequestTest() );
		runner.addCase( new ufront.web.context.HttpContextTest() );
		runner.addCase( new ufront.web.DefaultUfrontConfigurationTest() );
		runner.addCase( new ufront.web.HttpCookieTest() );
		runner.addCase( new ufront.web.ControllerMacrosTest() );
		runner.addCase( new ufront.web.UserAgentTest() );
		runner.addCase( new ufront.web.session.InlineSessionMiddlewareTest() );
		runner.addCase( new ufront.web.session.VoidSessionTest() );
		runner.addCase( new ufront.web.session.FileSessionTest() );
		runner.addCase( new ufront.web.result.DetoxResultTest() );
		runner.addCase( new ufront.web.result.ViewResultTest() );
		runner.addCase( new ufront.web.result.ContentResultTest() );
		runner.addCase( new ufront.web.result.RedirectResultTest() );
		runner.addCase( new ufront.web.result.FileResultTest() );
		runner.addCase( new ufront.web.result.JsonResultTest() );
		runner.addCase( new ufront.web.result.BytesResultTest() );
		runner.addCase( new ufront.web.result.EmptyResultTest() );
		runner.addCase( new ufront.web.result.FilePathResultTest() );
		runner.addCase( new ufront.web.result.ActionResultTest() );
		runner.addCase( new ufront.web.url.PartialUrlTest() );
		runner.addCase( new ufront.web.url.filter.DirectoryUrlFilterTest() );
		runner.addCase( new ufront.web.url.filter.SegmentToParamUrlFilterTest() );
		runner.addCase( new ufront.web.url.filter.QueryStringUrlFilterTest() );
		runner.addCase( new ufront.web.url.filter.PathInfoUrlFilterTest() );
		runner.addCase( new ufront.web.url.VirtualUrlTest() );
		runner.addCase( new ufront.web.ControllerTest() );
		runner.addCase( new ufront.web.upload.TmpFileUploadSyncTest() );
		runner.addCase( new ufront.web.upload.TmpFileUploadMiddlewareTest() );
		runner.addCase( new ufront.web.DispatchTest() );
		runner.addCase( new ufront.web.DefaultControllerTest() );
		runner.addCase( new ufront.web.UfrontConfigurationTest() );
		runner.addCase( new ufront.view.UFViewEngineTest() );
		runner.addCase( new ufront.view.FileViewEngineTest() );
		runner.addCase( new ufront.view.TemplateDataTest() );
		runner.addCase( new ufront.view.TemplatingEnginesTest() );
		runner.addCase( new ufront.view.UFTemplateTest() );
		runner.addCase( new ufront.api.ApiMacrosTest() );
		runner.addCase( new ufront.api.UFApiTest() );
		runner.addCase( new ufront.api.UFApiContextTest() );
		runner.addCase( new ufront.cache.MemoryCacheTest() );
		runner.addCase( new ufront.sys.SysUtilTest() );
		runner.addCase( new ufront.test.TestUtilsTest() );
		runner.addCase( new ufront.auth.YesBossAuthHandlerTest() );
		runner.addCase( new haxe.remoting.RemotingUtilTest() );
		runner.addCase( new haxe.remoting.HttpAsyncConnectionWithTracesTest() );
		runner.addCase( new haxe.remoting.HttpConnectionWithTracesTest() );
	}
}
